spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: user
    password:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email


app:
  jwt:
    secret: ${JWT_SECRET}
    expiration:
      minutes: 20
  oauth2:
    redirectUri: http://localhost:8080/oauth2/redirect
  cors:
    allowed-origins: http://localhost:8080

logging:
  level:
    org.springframework.security: DEBUG