spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: user
    password:
  h2:
    console:
      enabled: true
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}
#            scope: read:user, user:email
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope: profile, email


app:
  jwt:
    secret: asdasdasdasdasdasdasdsadasdasdasdasdadasdasdasdasdasdasdasdasdasdasdsadasdasd
    expiration:
      minutes: 20

logging:
  level:
    org.springframework.security: DEBUG