spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: user
    password:
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: '98363996a501f1032430'
            client-secret: 'd7cf9d00926beb1b5d1f11e7afff6730a91e3f8a'
            scope: read:user, user:email


app:
  jwt:
    secret: asdasdasdasdasdasdasdsadasdasdasdasdadasdasdasdasdasdasdasdasdasdasdsadasdasd
    expiration:
      minutes: 20

logging:
  level:
    org.springframework.security: DEBUG